/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as PrivateAccountRouteImport } from './routes/_private/_account'
import { Route as PrivateFavoritosRouteImport } from './routes/_private/favoritos'
import { Route as PrivatePagamentoRouteImport } from './routes/_private/pagamento'
import { Route as NftNftIdRouteImport } from './routes/nft.$nftId'
import { Route as PrivateAccountCarteirasRouteImport } from './routes/_private/_account/carteiras'
import { Route as PrivateAccountPerfilRouteImport } from './routes/_private/_account/perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAccountRoute = PrivateAccountRouteImport.update({
  id: '/_account',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateFavoritosRoute = PrivateFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivatePagamentoRoute = PrivatePagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => PrivateRoute,
} as any)
const NftNftIdRoute = NftNftIdRouteImport.update({
  id: '/nft/$nftId',
  path: '/nft/$nftId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAccountCarteirasRoute = PrivateAccountCarteirasRouteImport.update({
  id: '/carteiras',
  path: '/carteiras',
  getParentRoute: () => PrivateAccountRoute,
} as any)
const PrivateAccountPerfilRoute = PrivateAccountPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PrivateAccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/mercado': typeof MercadoRoute
  '/favoritos': typeof PrivateFavoritosRoute
  '/pagamento': typeof PrivatePagamentoRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/carteiras': typeof PrivateAccountCarteirasRoute
  '/perfil': typeof PrivateAccountPerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/mercado': typeof MercadoRoute
  '/favoritos': typeof PrivateFavoritosRoute
  '/pagamento': typeof PrivatePagamentoRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/carteiras': typeof PrivateAccountCarteirasRoute
  '/perfil': typeof PrivateAccountPerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteWithChildren
  '/carrinho': typeof CarrinhoRoute
  '/mercado': typeof MercadoRoute
  '/_private/_account': typeof PrivateAccountRouteWithChildren
  '/_private/favoritos': typeof PrivateFavoritosRoute
  '/_private/pagamento': typeof PrivatePagamentoRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/_private/_account/carteiras': typeof PrivateAccountCarteirasRoute
  '/_private/_account/perfil': typeof PrivateAccountPerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrinho'
    | '/mercado'
    | '/favoritos'
    | '/pagamento'
    | '/nft/$nftId'
    | '/carteiras'
    | '/perfil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/mercado'
    | '/favoritos'
    | '/pagamento'
    | '/nft/$nftId'
    | '/carteiras'
    | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/carrinho'
    | '/mercado'
    | '/_private/_account'
    | '/_private/favoritos'
    | '/_private/pagamento'
    | '/nft/$nftId'
    | '/_private/_account/carteiras'
    | '/_private/_account/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  CarrinhoRoute: typeof CarrinhoRoute
  MercadoRoute: typeof MercadoRoute
  NftNftIdRoute: typeof NftNftIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/_account': {
      id: '/_private/_account'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateAccountRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/favoritos': {
      id: '/_private/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof PrivateFavoritosRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/pagamento': {
      id: '/_private/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PrivatePagamentoRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/nft/$nftId': {
      id: '/nft/$nftId'
      path: '/nft/$nftId'
      fullPath: '/nft/$nftId'
      preLoaderRoute: typeof NftNftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/_account/carteiras': {
      id: '/_private/_account/carteiras'
      path: '/carteiras'
      fullPath: '/carteiras'
      preLoaderRoute: typeof PrivateAccountCarteirasRouteImport
      parentRoute: typeof PrivateAccountRoute
    }
    '/_private/_account/perfil': {
      id: '/_private/_account/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PrivateAccountPerfilRouteImport
      parentRoute: typeof PrivateAccountRoute
    }
  }
}

interface PrivateAccountRouteChildren {
  PrivateAccountCarteirasRoute: typeof PrivateAccountCarteirasRoute
  PrivateAccountPerfilRoute: typeof PrivateAccountPerfilRoute
}

const PrivateAccountRouteChildren: PrivateAccountRouteChildren = {
  PrivateAccountCarteirasRoute: PrivateAccountCarteirasRoute,
  PrivateAccountPerfilRoute: PrivateAccountPerfilRoute,
}

const PrivateAccountRouteWithChildren = PrivateAccountRoute._addFileChildren(
  PrivateAccountRouteChildren,
)

interface PrivateRouteChildren {
  PrivateAccountRoute: typeof PrivateAccountRouteWithChildren
  PrivateFavoritosRoute: typeof PrivateFavoritosRoute
  PrivatePagamentoRoute: typeof PrivatePagamentoRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateAccountRoute: PrivateAccountRouteWithChildren,
  PrivateFavoritosRoute: PrivateFavoritosRoute,
  PrivatePagamentoRoute: PrivatePagamentoRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  CarrinhoRoute: CarrinhoRoute,
  MercadoRoute: MercadoRoute,
  NftNftIdRoute: NftNftIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
